/* Domain.c generated by valac 0.10.0, the Vala compiler
 * generated from Domain.vala, do not modify */

/* Domain.vala
 *
 * Copyright (C) 2010  Joel Marty
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Author:
 * 	Joel Marty <10093745@brookes.ac.uk>
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define GNOMECOOK_DOMAIN_TYPE_MEAL (gnomecook_domain_meal_get_type ())
#define GNOMECOOK_DOMAIN_MEAL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMECOOK_DOMAIN_TYPE_MEAL, gnomecookDomainMeal))
#define GNOMECOOK_DOMAIN_MEAL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMECOOK_DOMAIN_TYPE_MEAL, gnomecookDomainMealClass))
#define GNOMECOOK_DOMAIN_IS_MEAL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMECOOK_DOMAIN_TYPE_MEAL))
#define GNOMECOOK_DOMAIN_IS_MEAL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMECOOK_DOMAIN_TYPE_MEAL))
#define GNOMECOOK_DOMAIN_MEAL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMECOOK_DOMAIN_TYPE_MEAL, gnomecookDomainMealClass))

typedef struct _gnomecookDomainMeal gnomecookDomainMeal;
typedef struct _gnomecookDomainMealClass gnomecookDomainMealClass;
typedef struct _gnomecookDomainMealPrivate gnomecookDomainMealPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _gnomecookDomainMeal {
	GObject parent_instance;
	gnomecookDomainMealPrivate * priv;
};

struct _gnomecookDomainMealClass {
	GObjectClass parent_class;
};

struct _gnomecookDomainMealPrivate {
	gint64 _id;
	char* _name;
	char* _ingredients;
	double _cooking_time;
	char* _instructions;
	double _rating;
};


static gpointer gnomecook_domain_meal_parent_class = NULL;

GType gnomecook_domain_meal_get_type (void) G_GNUC_CONST;
#define GNOMECOOK_DOMAIN_MEAL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GNOMECOOK_DOMAIN_TYPE_MEAL, gnomecookDomainMealPrivate))
enum  {
	GNOMECOOK_DOMAIN_MEAL_DUMMY_PROPERTY,
	GNOMECOOK_DOMAIN_MEAL_ID,
	GNOMECOOK_DOMAIN_MEAL_NAME,
	GNOMECOOK_DOMAIN_MEAL_INGREDIENTS,
	GNOMECOOK_DOMAIN_MEAL_COOKING_TIME,
	GNOMECOOK_DOMAIN_MEAL_INSTRUCTIONS,
	GNOMECOOK_DOMAIN_MEAL_RATING
};
gnomecookDomainMeal* gnomecook_domain_meal_new (void);
gnomecookDomainMeal* gnomecook_domain_meal_construct (GType object_type);
gint64 gnomecook_domain_meal_get_id (gnomecookDomainMeal* self);
void gnomecook_domain_meal_set_id (gnomecookDomainMeal* self, gint64 value);
const char* gnomecook_domain_meal_get_name (gnomecookDomainMeal* self);
void gnomecook_domain_meal_set_name (gnomecookDomainMeal* self, const char* value);
const char* gnomecook_domain_meal_get_ingredients (gnomecookDomainMeal* self);
void gnomecook_domain_meal_set_ingredients (gnomecookDomainMeal* self, const char* value);
double gnomecook_domain_meal_get_cooking_time (gnomecookDomainMeal* self);
void gnomecook_domain_meal_set_cooking_time (gnomecookDomainMeal* self, double value);
const char* gnomecook_domain_meal_get_instructions (gnomecookDomainMeal* self);
void gnomecook_domain_meal_set_instructions (gnomecookDomainMeal* self, const char* value);
double gnomecook_domain_meal_get_rating (gnomecookDomainMeal* self);
void gnomecook_domain_meal_set_rating (gnomecookDomainMeal* self, double value);
static void gnomecook_domain_meal_finalize (GObject* obj);
static void gnomecook_domain_meal_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void gnomecook_domain_meal_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);



#line 27 "Domain.vala"
gnomecookDomainMeal* gnomecook_domain_meal_construct (GType object_type) {
#line 100 "Domain.c"
	gnomecookDomainMeal * self;
#line 27 "Domain.vala"
	self = (gnomecookDomainMeal*) g_object_new (object_type, NULL);
#line 104 "Domain.c"
	return self;
}


#line 27 "Domain.vala"
gnomecookDomainMeal* gnomecook_domain_meal_new (void) {
#line 27 "Domain.vala"
	return gnomecook_domain_meal_construct (GNOMECOOK_DOMAIN_TYPE_MEAL);
#line 113 "Domain.c"
}


gint64 gnomecook_domain_meal_get_id (gnomecookDomainMeal* self) {
	gint64 result;
	g_return_val_if_fail (self != NULL, 0LL);
	result = self->priv->_id;
#line 29 "Domain.vala"
	return result;
#line 123 "Domain.c"
}


void gnomecook_domain_meal_set_id (gnomecookDomainMeal* self, gint64 value) {
	g_return_if_fail (self != NULL);
	self->priv->_id = value;
	g_object_notify ((GObject *) self, "id");
}


const char* gnomecook_domain_meal_get_name (gnomecookDomainMeal* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_name;
#line 30 "Domain.vala"
	return result;
#line 140 "Domain.c"
}


void gnomecook_domain_meal_set_name (gnomecookDomainMeal* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_name = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_name), _tmp0_);
	g_object_notify ((GObject *) self, "name");
}


const char* gnomecook_domain_meal_get_ingredients (gnomecookDomainMeal* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_ingredients;
#line 31 "Domain.vala"
	return result;
#line 158 "Domain.c"
}


void gnomecook_domain_meal_set_ingredients (gnomecookDomainMeal* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_ingredients = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_ingredients), _tmp0_);
	g_object_notify ((GObject *) self, "ingredients");
}


double gnomecook_domain_meal_get_cooking_time (gnomecookDomainMeal* self) {
	double result;
	g_return_val_if_fail (self != NULL, 0.0);
	result = self->priv->_cooking_time;
#line 32 "Domain.vala"
	return result;
#line 176 "Domain.c"
}


void gnomecook_domain_meal_set_cooking_time (gnomecookDomainMeal* self, double value) {
	g_return_if_fail (self != NULL);
	self->priv->_cooking_time = value;
	g_object_notify ((GObject *) self, "cooking-time");
}


const char* gnomecook_domain_meal_get_instructions (gnomecookDomainMeal* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_instructions;
#line 33 "Domain.vala"
	return result;
#line 193 "Domain.c"
}


void gnomecook_domain_meal_set_instructions (gnomecookDomainMeal* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_instructions = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_instructions), _tmp0_);
	g_object_notify ((GObject *) self, "instructions");
}


double gnomecook_domain_meal_get_rating (gnomecookDomainMeal* self) {
	double result;
	g_return_val_if_fail (self != NULL, 0.0);
	result = self->priv->_rating;
#line 34 "Domain.vala"
	return result;
#line 211 "Domain.c"
}


void gnomecook_domain_meal_set_rating (gnomecookDomainMeal* self, double value) {
	g_return_if_fail (self != NULL);
	self->priv->_rating = value;
	g_object_notify ((GObject *) self, "rating");
}


static void gnomecook_domain_meal_class_init (gnomecookDomainMealClass * klass) {
	gnomecook_domain_meal_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (gnomecookDomainMealPrivate));
	G_OBJECT_CLASS (klass)->get_property = gnomecook_domain_meal_get_property;
	G_OBJECT_CLASS (klass)->set_property = gnomecook_domain_meal_set_property;
	G_OBJECT_CLASS (klass)->finalize = gnomecook_domain_meal_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMECOOK_DOMAIN_MEAL_ID, g_param_spec_int64 ("id", "id", "id", G_MININT64, G_MAXINT64, (gint64) 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMECOOK_DOMAIN_MEAL_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMECOOK_DOMAIN_MEAL_INGREDIENTS, g_param_spec_string ("ingredients", "ingredients", "ingredients", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMECOOK_DOMAIN_MEAL_COOKING_TIME, g_param_spec_double ("cooking-time", "cooking-time", "cooking-time", -G_MAXDOUBLE, G_MAXDOUBLE, (double) 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMECOOK_DOMAIN_MEAL_INSTRUCTIONS, g_param_spec_string ("instructions", "instructions", "instructions", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMECOOK_DOMAIN_MEAL_RATING, g_param_spec_double ("rating", "rating", "rating", -G_MAXDOUBLE, G_MAXDOUBLE, (double) 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void gnomecook_domain_meal_instance_init (gnomecookDomainMeal * self) {
	self->priv = GNOMECOOK_DOMAIN_MEAL_GET_PRIVATE (self);
	self->priv->_id = (gint64) 0;
	self->priv->_name = g_strdup ("new recipe");
	self->priv->_ingredients = g_strdup ("");
	self->priv->_cooking_time = (double) 0;
	self->priv->_instructions = g_strdup ("");
	self->priv->_rating = (double) 0;
}


static void gnomecook_domain_meal_finalize (GObject* obj) {
	gnomecookDomainMeal * self;
	self = GNOMECOOK_DOMAIN_MEAL (obj);
	_g_free0 (self->priv->_name);
	_g_free0 (self->priv->_ingredients);
	_g_free0 (self->priv->_instructions);
	G_OBJECT_CLASS (gnomecook_domain_meal_parent_class)->finalize (obj);
}


GType gnomecook_domain_meal_get_type (void) {
	static volatile gsize gnomecook_domain_meal_type_id__volatile = 0;
	if (g_once_init_enter (&gnomecook_domain_meal_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (gnomecookDomainMealClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gnomecook_domain_meal_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (gnomecookDomainMeal), 0, (GInstanceInitFunc) gnomecook_domain_meal_instance_init, NULL };
		GType gnomecook_domain_meal_type_id;
		gnomecook_domain_meal_type_id = g_type_register_static (G_TYPE_OBJECT, "gnomecookDomainMeal", &g_define_type_info, 0);
		g_once_init_leave (&gnomecook_domain_meal_type_id__volatile, gnomecook_domain_meal_type_id);
	}
	return gnomecook_domain_meal_type_id__volatile;
}


static void gnomecook_domain_meal_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	gnomecookDomainMeal * self;
	self = GNOMECOOK_DOMAIN_MEAL (object);
	switch (property_id) {
		case GNOMECOOK_DOMAIN_MEAL_ID:
		g_value_set_int64 (value, gnomecook_domain_meal_get_id (self));
		break;
		case GNOMECOOK_DOMAIN_MEAL_NAME:
		g_value_set_string (value, gnomecook_domain_meal_get_name (self));
		break;
		case GNOMECOOK_DOMAIN_MEAL_INGREDIENTS:
		g_value_set_string (value, gnomecook_domain_meal_get_ingredients (self));
		break;
		case GNOMECOOK_DOMAIN_MEAL_COOKING_TIME:
		g_value_set_double (value, gnomecook_domain_meal_get_cooking_time (self));
		break;
		case GNOMECOOK_DOMAIN_MEAL_INSTRUCTIONS:
		g_value_set_string (value, gnomecook_domain_meal_get_instructions (self));
		break;
		case GNOMECOOK_DOMAIN_MEAL_RATING:
		g_value_set_double (value, gnomecook_domain_meal_get_rating (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void gnomecook_domain_meal_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	gnomecookDomainMeal * self;
	self = GNOMECOOK_DOMAIN_MEAL (object);
	switch (property_id) {
		case GNOMECOOK_DOMAIN_MEAL_ID:
		gnomecook_domain_meal_set_id (self, g_value_get_int64 (value));
		break;
		case GNOMECOOK_DOMAIN_MEAL_NAME:
		gnomecook_domain_meal_set_name (self, g_value_get_string (value));
		break;
		case GNOMECOOK_DOMAIN_MEAL_INGREDIENTS:
		gnomecook_domain_meal_set_ingredients (self, g_value_get_string (value));
		break;
		case GNOMECOOK_DOMAIN_MEAL_COOKING_TIME:
		gnomecook_domain_meal_set_cooking_time (self, g_value_get_double (value));
		break;
		case GNOMECOOK_DOMAIN_MEAL_INSTRUCTIONS:
		gnomecook_domain_meal_set_instructions (self, g_value_get_string (value));
		break;
		case GNOMECOOK_DOMAIN_MEAL_RATING:
		gnomecook_domain_meal_set_rating (self, g_value_get_double (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




