/* main.c generated by valac 0.10.0, the Vala compiler
 * generated from main.vala, do not modify */

/* main.vala
 *
 * Copyright (C) 2010  Joel Marty
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Author:
 * 	Joel Marty <10093745@brookes.ac.uk>
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;

#define GNOMECOOK_UI_TYPE_APPLICATION (gnomecook_ui_application_get_type ())
#define GNOMECOOK_UI_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMECOOK_UI_TYPE_APPLICATION, gnomecookuiApplication))
#define GNOMECOOK_UI_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMECOOK_UI_TYPE_APPLICATION, gnomecookuiApplicationClass))
#define GNOMECOOK_UI_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMECOOK_UI_TYPE_APPLICATION))
#define GNOMECOOK_UI_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMECOOK_UI_TYPE_APPLICATION))
#define GNOMECOOK_UI_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMECOOK_UI_TYPE_APPLICATION, gnomecookuiApplicationClass))

typedef struct _gnomecookuiApplication gnomecookuiApplication;
typedef struct _gnomecookuiApplicationClass gnomecookuiApplicationClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _Main {
	GObject parent_instance;
	MainPrivate * priv;
};

struct _MainClass {
	GObjectClass parent_class;
};


static gpointer main_parent_class = NULL;

GType main_get_type (void) G_GNUC_CONST;
enum  {
	MAIN_DUMMY_PROPERTY
};
static gint main_main (char** args, int args_length1);
gnomecookuiApplication* gnomecook_ui_application_new (char** args, int args_length1);
gnomecookuiApplication* gnomecook_ui_application_construct (GType object_type, char** args, int args_length1);
GType gnomecook_ui_application_get_type (void) G_GNUC_CONST;
Main* main_new (void);
Main* main_construct (GType object_type);



#line 27 "main.vala"
static gint main_main (char** args, int args_length1) {
#line 81 "main.c"
	gint result = 0;
	gnomecookuiApplication* app;
#line 28 "main.vala"
	app = gnomecook_ui_application_new (args, args_length1);
#line 86 "main.c"
	result = 0;
	_g_object_unref0 (app);
#line 30 "main.vala"
	return result;
#line 91 "main.c"
}


#line 27 "main.vala"
int main (int argc, char ** argv) {
#line 97 "main.c"
	g_thread_init (NULL);
#line 27 "main.vala"
	g_type_init ();
#line 27 "main.vala"
	return main_main (argv, argc);
#line 103 "main.c"
}


#line 25 "main.vala"
Main* main_construct (GType object_type) {
#line 109 "main.c"
	Main * self;
#line 25 "main.vala"
	self = (Main*) g_object_new (object_type, NULL);
#line 113 "main.c"
	return self;
}


#line 25 "main.vala"
Main* main_new (void) {
#line 25 "main.vala"
	return main_construct (TYPE_MAIN);
#line 122 "main.c"
}


static void main_class_init (MainClass * klass) {
	main_parent_class = g_type_class_peek_parent (klass);
}


static void main_instance_init (Main * self) {
}


GType main_get_type (void) {
	static volatile gsize main_type_id__volatile = 0;
	if (g_once_init_enter (&main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, NULL };
		GType main_type_id;
		main_type_id = g_type_register_static (G_TYPE_OBJECT, "Main", &g_define_type_info, 0);
		g_once_init_leave (&main_type_id__volatile, main_type_id);
	}
	return main_type_id__volatile;
}




